# Generated by Django 3.2.6 on 2021-08-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('body', models.TextField(verbose_name='diary body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='diary created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='diary updated date')),
            ],
        ),
    ]
