# Generated by Django 3.2.8 on 2022-12-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalDiary', '0002_diary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.CharField(default='n', max_length=50, verbose_name='mood'),
        ),
    ]
